### ISSUE TITLE
Feature request: Diff/Compare only selected file(s)

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-git-control#12]
At the moment the **Compare** button shows a diff of all changes, and ideally when I have one file selected (see below) I would like to just see that file

![image](https://cloud.githubusercontent.com/assets/656739/5690976/6baa7d0a-98a7-11e4-90a6-c8ee1a3cd298.png)

This would help when the workflow is:

1. select file
2. review changes
3. chose to reset those changes
4. move to next file (i.e. 1. ) until all files are reviewed
5. commit

**Comment by jacogr** [comment]
+1

**Comment by Trudko** [comment]
+1

**Comment by gmlnchv** [comment]
+1

**Comment by neo-inuit** [comment]
+1

**Comment by hellerbarde** [comment]
Right now, there is no way to "select" a file. Only to click on it, and thus (sort of) stage it for commit. So it would be useful to click on a file, which selects it (semantics of a file browser). Then it would display the diff for this file only.

But how to get back to the diff of all files? Any ideas?
