### ISSUE TITLE
Add a pull from upstream button

### ISSUE THREAD

**Issue by Huaraz2** [jacogr/atom-git-control#125]
In order to pull from upstream at the moment i have to use the terminal, this is not a major problem but is there a way to add this feature to the package?

**Comment by MarcelMue** [comment]
There was some discussion ( see #44 ) about github exclusive features. I am unsure about pulling from upstream but am willing to discuss it if someone wants to work on a PR for it.

**Comment by Huaraz2** [comment]
In the menu-veiw.coffee file you have used the code:  
`{ id: 'pull', menu: 'Pull', icon: 'pull', type: 'upstream'}`  
to put the pull button into the menu. Why is the 'type' set as upstream? dhould it not be origin as that is the git remote it uses.

**Comment by Huaraz2** [comment]
Also if I wanted to look at where the `id` is (see the code in my last comment), would I be right in going to the git.coffeefile and looking at the code from line 99 onwards?

Thanks :smiling_imp:
