### ISSUE TITLE
Package updates

### ISSUE THREAD

**Issue by alexandernst** [jacogr/atom-git-control#148]
I see that there were quite some updates in the package, but I can't see those changes in Atom's package manager. The latest version I see there is `0.4.0`. Is that expected?

**Comment by mbroo** [comment]
Also wondering about this same issue. Atom lists 0.4.0 as the latest.

**Comment by MarcelMue** [comment]
Latest shouldb be 0.8.2, not sure why Atom thinks it's 0.4.0
