### ISSUE TITLE
/bin/sh: git: command not found 

### ISSUE THREAD

**Issue by emveeoh** [jacogr/atom-git-control#156]
Full Error Message:

> git status --porcelain --untracked-files=all
> /bin/sh: git: command not found
> 'git status --porcelain --untracked-files=all' exited with error code 127

**Comment by ericstroo** [comment]
Same issue here, I think it's because Atom (when launched from the desktop or spotlight) doesn't inherit the PATH settings. Try launching atom from the CLI and see if the error persists. To fix it, I added: https://github.com/hurrymaplelad/atom-fix-path
