### ISSUE TITLE
Publish latest 0.7 version in atom.io

### ISSUE THREAD

**Issue by mrsoto** [jacogr/atom-git-control#165]
The available version in [atom.io](https://atom.io/packages/git-control) is the old 0.4.0 which doesn't include several enhances like multi-project.

**Comment by jacogr** [comment]
Yes, sadly apm publish fails ... repeatedly. I'll re-try again, slipped my mind after the last 2-3 hours trying to get it sorted.

**Comment by jacogr** [comment]
Pushed as 0.7.1
