### ISSUE TITLE
Project list contains only 'undefied' on windows

### ISSUE THREAD

**Issue by ntrf** [jacogr/atom-git-control#168]
The repository path is being parsed with the asumption that path will be delimited by `/` and the last folder will be `.git` (as seen in [project-dialog.coffee line 32](https://github.com/jacogr/atom-git-control/blob/master/lib/dialogs/project-dialog.coffee#L32)). This fails on windows, scince all paths on windows are separated by `\` symbol. You can use node.js [path api](https://nodejs.org/api/path.html#path_path_parse_pathstring) in order to handle path parsing properly and [getWorkingDirectory](https://atom.io/docs/api/v1.0.19/GitRepository#instance-getWorkingDirectory) function to get path without `.git` suffix.

```
path = require 'path'
...
path.parse(repo.getWorkingDirectory()).name
```

**Comment by trahloff** [comment]
+1

**Comment by apazga** [comment]
+1. Attached screenshot.

![atom-undefined](https://cloud.githubusercontent.com/assets/6894350/14427051/f1f09d3c-fff2-11e5-8a0e-be253f94f615.png)
