### ISSUE TITLE
git-control doesn't work anymore

### ISSUE THREAD

**Issue by hellfish2** [jacogr/atom-git-control#18]
any suggest? git-control doesn't show up 
![screenshot from 2015-01-18 22 51 14](https://cloud.githubusercontent.com/assets/2073636/5795560/8dfe2d84-9f64-11e4-9ba6-a0b9dc06ae42.png)

**Comment by KapuzenSohn** [comment]
It works for me perferkt.
Maybe reinstalling it?

Atom Verion: 0.175.0-60970d6 (Build from the Master branch)

**Comment by ginus** [comment]
In my Atom Verion: 0.174.0 it will crush whole atom programe

**Comment by ffsantos92** [comment]
I'm using git-control v0.1.8 with atom v0.175.0 and it's working fine.

**Comment by MarcelMue** [comment]
Issue is too vague and I am unable to replicate it.
