### ISSUE TITLE
pull push fech not working (ssh?)

### ISSUE THREAD

**Issue by an1rk4** [jacogr/atom-git-control#200]
windows 10 
win cmd git pull/push not working. i use git bush

git conrol panel

i have errors 
![image](https://cloud.githubusercontent.com/assets/1837509/18656706/e23a7b26-7f0c-11e6-8a1c-90a84aa1bdb7.png)

no active buttons pull and push

no ssh password popup

p.s Sorry for my English

**Comment by dpendolino** [comment]
I just had this issue on Arch Linux and needed to install the `x11-ssh-askpass` package so it would prompt me for me ssh key passphrase. Still I think it should really hook into an auth agent so a password isn't needed for any operation.
