### ISSUE TITLE
Diff files after clicking on them

### ISSUE THREAD

**Issue by Trudko** [jacogr/atom-git-control#22]
When I am staging files, I am going one by one to review to changes before staging them. I would like to see diff of file after clicking on them in right panel.

**Comment by neo-inuit** [comment]
Same process for me, this feature will be great !

**Comment by MarcelMue** [comment]
Opening files from the compare panel now works ( version 0.2.0 ) , however the diff isn't shown in the file.

**Comment by dflock** [comment]
:+1:

**Comment by zwacky** [comment]
this is such an important enhancement and keeps me from using git-control entirely.

would you be open for PR for this?
