### ISSUE TITLE
Pane.addItem is deprecated.

### ISSUE THREAD

**Issue by edarblanco** [jacogr/atom-git-control#225]
Pane::addItem(item, 0) is deprecated in favor of Pane::addItem(item, {index: 0})
```
Pane.addItem (/usr/lib/atom/src/pane.js:447:14)
Object.toggleView (/home/edar/.atom/packages/git-control/lib/git-control.coffee:50:21)
atom-workspace.<anonymous> (/home/edar/.atom/packages/git-control/lib/git-control.coffee:27:24)
CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:160:19)
```

**Comment by fr4nk** [comment]
If nobody minds I would quickly fix this and make a pull-request. Wil be done in a minute... ;-)

**Comment by iamchriswick** [comment]
Still get the deprecation message, and I just installed

**Comment by felipebhz** [comment]
Same here. Just installed today, and still getting this deprecation warning. :-)

**Comment by Jecko-o** [comment]
Same here.

**Comment by christianodejesus** [comment]
Same here. I'm running Atom 1.13.1 x64 version in OS X El Capitan.

**Comment by tadinski** [comment]
+1 same problem

**Comment by michalsarna** [comment]
+1 same for me

**Comment by diegobiavati** [comment]
+ same problem

**Comment by Kelvinmijaya** [comment]
same for me

**Comment by ichbinder** [comment]
+1 same for me, Linux

**Comment by aflatto** [comment]
+1 for me , Atom  1.14.1 x64 on Fedora 24

**Comment by TBusen** [comment]
+1 Win7, Atom 1.14.3

**Comment by hoquangthaiholy** [comment]
+1 Win10, Atom 1.14.3

**Comment by efc** [comment]
+1 macOS, Atom 1.14.3

**Comment by mikedizon** [comment]
+1 macOS, Atom 1.14.3

**Comment by angelxaces** [comment]
+1 macOS, Atom 1.14.3

**Comment by PerikiyoXD** [comment]
+1 Xubuntu, Atom 1.14.3

**Comment by Huaraz2** [comment]
+1 Ubuntu, Atom 1.14.4

**Comment by BrenMurrell** [comment]
+1 Windows 10, Atom 1.14.4

**Comment by GeorgeWL** [comment]
Deprecation Cop still tracks this as a deprecation

Is it a problem with deprecation cop or was this never actually fixed?

**Comment by lwincenciak** [comment]
+1 here, Win7, Atom 1.14.4

**Comment by dacacioa** [comment]
+1 here, Win 10, Atom 1.15.0

**Comment by lacostenycoder** [comment]
+1 Mac OS 10.11.6, Atom 1.15.0 x64

**Comment by bhusang** [comment]
+1 here, Win 10, Atom 1.15.0

**Comment by rashagen** [comment]
+1, Mac 10.12.3, Atom 1.15.0

**Comment by carreirorco** [comment]
+1, Ubuntu 16.04.2 LTS, Atom 1.15.0

**Comment by GeorgeWL** [comment]
#233 might be the reason @carreirorco

**Comment by blairg** [comment]
Getting this on osx 10.11.6 with Atom 1.15.0 x64 
Pane::addItem(item, 0) is deprecated in favor of Pane::addItem(item, {index: 0})

**Comment by GeorgeWL** [comment]
see #233 @blairg

**Comment by MarcelMue** [comment]
Merged #222 - to be included in the next minor release.

**Comment by akaybagorov** [comment]
+1

**Comment by SpeedrunnerG55** [comment]
+1

**Comment by rpgzzang0613** [comment]
+1 Windows10 Atom 1.15.0

**Comment by miguelmendesnet** [comment]
+1 Mac OS 10.12.3, Atom 1.15.0 x64

**Comment by GeorgeWL** [comment]
@akaybagorov @SpeedrunnerG55 @rpgzzang0613 @miguelmendesnet 

See: https://github.com/jacogr/atom-git-control/issues/225#issuecomment-289303862

**Comment by NetMango** [comment]
+1 Ubuntu 16.04.2 Atom 1.15.0 x64

**Comment by adrianvanlan** [comment]
+1

**Comment by iamchriswick** [comment]
People! It's 2017! Use the reaction feature instead of "+1"...

<img width="254" alt="screen shot 2017-04-03 at 19 45 20" src="https://cloud.githubusercontent.com/assets/1186755/24622688/22e086ec-18a6-11e7-88c9-873a9c282b1c.png">

**Comment by MarcelMue** [comment]
Fix is now live in version 0.9.0

**Comment by GeorgeWL** [comment]
@iamchriswick

I feel like github.com should be smart enough to convert it tbh. 

And to do the same with the API.

**Comment by iamchriswick** [comment]
@GeorgeWL Thats the same as asking Facebook to "convert" when someone types "Like" in a comment to be a Like-reaction on the main post. 😂

**Comment by GeorgeWL** [comment]
@iamchriswick hairy fluff that yeah
