### ISSUE TITLE
Is this repository still active? Last Commit in the log is from July 2016.

### ISSUE THREAD

**Issue by GeorgeWL** [jacogr/atom-git-control#233]
https://github.com/jacogr/atom-git-control/commit/2bdff4faeb01cb9a64feef8ce1ae18cf550a4691

Is the most recent commit actually in the logs. 

And Issues are building up with folks mentioning solutions but none of the Pull-Requests being accepted.

If not we have two options: 

1. Fork the project and reupload it to Atom packages with a different name
2. Contact the repo administrators directly through e-mail/social-media and ask for them to pass ownership to someone who can take control back.

**Comment by iamchriswick** [comment]
Agreed @GeorgeWL 👍

The GitHub he logs shows that @jacogr was active on March 17th, so it's not like he's not seeing the comments, but more likely that he's ignoring them...

**Comment by MarcelMue** [comment]
Hey guys,
I was extremely busy with life for quite a while now. I didn't really know how bad the situation had gotten since I blocked out most stuff from this repo due to it spamming other (relatively) more important stuff.

I am not sure how active @jacogr has been the past few month or how much he plans to contribute. I will have some more time in the upcoming weeks and plan to contribute again.

I would be very thankful if you can point me to outstanding / very important pull requests, so that I can prioritize those while I get going again.

**Comment by GeorgeWL** [comment]
@marcelmue it's okay, life happens sometimes :)

there's some issues with deprecated calls (one of which this topic had been referenced in has a pull request that solves that's sat waiting to merge)

**Comment by GeorgeWL** [comment]
#225

**Comment by MarcelMue** [comment]
I merged #222 since it was just a very straight forward one liner.

If someone has the time, please test the changes in #231

**Comment by ProPuke** [comment]
There's a critical issue [here](https://github.com/jacogr/atom-git-control/issues/123#issuecomment-272965199) that needs addressing, hopefully before it catches anyone else out.

**Comment by MarcelMue** [comment]
I just released the new minor (0.9.0) with a few cosmetic changes and fixes for deprecation warnings (AKA nothing should have been broken on accident).

Going to need a bit more time and/or help for the more critical issues.

**Comment by shaharsol** [comment]
May I suggest using http://vizsla.io/ for this project? Can help both developers AND community.

**Comment by GeorgeWL** [comment]
think we'd rather use something we know works. @shaharsol 

has your account been hacked btw?

**Comment by shaharsol** [comment]
@GeorgeWL god forbid why do u think it got hacked?

**Comment by GeorgeWL** [comment]
seemed a little spammy and unwarranted was all.

**Comment by shaharsol** [comment]
@GeorgeWL I can see why and sorry for that. Look, I use git-control my own and got to this issue via a google search when helping a friend of mine with a problem he's having and realized this project has gotten to a very popular situation many successful OS projects tend to find themselves in: A lot of good will to start with, then a growing user base with a lot of issues, then they developers simply can't handle the work and desert. I am the developer of [Vizsla](http://vizsla.io) and know exactly when it comes handy and this is it... anyway, only meant good and didn't mean to spam.

**Comment by PascalPixel** [comment]
@shaharsol git management now comes built-in to atom (1.18.0 >)

**Comment by GeorgeWL** [comment]
Yeah tbh in 1.18.0+ this package is now defunct, the only thing slightly different though is it has some Git Flow features that the built-in doesn't.

But if the lead devs aren't going to be able to handle it anyway...this is likely dead. @Superpencil and @shaharsol
