### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by RangerMauve** [jacogr/atom-git-control#25]
It'd be nice if there was a way to have keyboard shortcuts for the different actions

**Comment by bobbyrenwick** [comment]
:+1: like SublimeGit.

**Comment by lmartins** [comment]
Would also love to have some shortcuts for this essential plugin.

**Comment by GradyD** [comment]
I would say that this is out of scope of this project and to take a look at https://atom.io/packages/git-plus

**Comment by RangerMauve** [comment]
Fair enough. I've been using them together lately, either way
