### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by montgomerykern** [jacogr/atom-git-control#27]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/montgomerykern/.atom/packages/git-control/lib/git-control.coffee:16:9)
```

**Comment by MarcelMue** [comment]
This is a duplicate issue of #16 . I will close all duplicates in order to clean up issues.
