### ISSUE TITLE
Unrecognized white spaces

### ISSUE THREAD

**Issue by Regaddi** [jacogr/atom-git-control#28]
Hi,

git-control does not recognize "white spaced" folders or files.
For example `project/samples/Hello World/config.xml` results in `project/samples/Hello` which is not a valid path inside the project.

**Comment by itaibh** [comment]
+1

**Comment by Christopher-Steel** [comment]
+1

**Comment by big-wave-tim** [comment]
just encountered this error with file names with spaces in them. Bug still exists in version 0.3.0 with atom 0.201.0 on windows 7. not a huge problem for me so not too concerned. 

Thanks devs for making git-control, its awesome !

**Comment by ghuber-github** [comment]
is it possible that this bug is still there in Version 1.0.11?
My file ```My Thesis.bib``` still results in 
```
fatal: pathspec '[...]/default_files/My' did not match any files
```

**Comment by Christopher-Steel** [comment]
I started a fix and a pull request but never finished it so it most
probably is still in there

**Comment by Platzer** [comment]
Do you figured out yet, what caused that issue why you cannot merge #74?

**Comment by ghuber-github** [comment]
kinda... it seemed that I couldn't type in my user git name and 
password. If I cache my settings with `credential.helper` [see 
here](https://help.github.com/articles/caching-your-github-password-in-git/)
I can type in my credentials once in a terminal, and after that 
`atom-git-control` seemed to work.

On 17.09.2015 15:19, Platzer wrote:
>
> Do you figured out yet, what caused that issue why you cannot merge 
> #74 <https://github.com/jacogr/atom-git-control/pull/74>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jacogr/atom-git-control/issues/28#issuecomment-141082058>.
>

-- 
Dipl.-Ing. Gerold Huber
Research Associate

Chair of Automatic Control Engineering (LSR)
TUM Department of Electrical, Electronic and Computer Engineering (EI)
Technische Universität München (TUM)
80333 Munich, Germany

Room No: N3509
Phone:   +49-89-289-23445
Fax:     +49-89-289-28340
E-Mail:  gerold.huber@tum.de
Web:     http://www.lsr.ei.tum.de

**Comment by michaelaye** [comment]
+1 but an un-fixed bug with such a wide spread effect since May makes me move on. I appreciate your effort, but I gotta keep productive.
