### ISSUE TITLE
Is Push Broken?

### ISSUE THREAD

**Issue by Virdari** [jacogr/atom-git-control#37]
I can't get the push button to work properly,
Made a change, it picks up the change, then i commit this new version. Now i try to push it onto the remote repository, which doesn't work. So what i do is after i commit it i use the Github Windows GUI to sync the local repo with the remote repo. ( isn't this exactly what the Push button is supposed to do?)

**Comment by davidmoret** [comment]
hi,
I've the same problem. It nothing happens when I press the push button. I'm on windows 7, I will try tonight on linux to see if I have the same problem.

**Comment by MarcelMue** [comment]
Discussion on this issue should continue on #7 .
