### ISSUE TITLE
Great plugin... still active development?

### ISSUE THREAD

**Issue by GradyD** [jacogr/atom-git-control#45]
Is this plugin still under development? It appears to have been dropped :-1:

**Comment by SerenadeX** [comment]
I hope it is.  This is a really helpful tool for atom.  I don't know what the goals are now with it.  I would love to be able to help it further in development.

**Comment by MarcelMue** [comment]
I would welcome a continuation of this repo aswell. Maybe another maintainer could be added.

**Comment by MarcelMue** [comment]
I am now a collaborator on this project and will continue active development. Jaco told me, that he is currently busy with his real life job.
