### ISSUE TITLE
] can not be typed on a AZERTY keyboard

### ISSUE THREAD

**Issue by kylekatarnls** [jacogr/atom-git-control#75]
Hi,

I cannot type a ] on my AZERTY keyboard (Ctrl + Alt + ")"), it trigger the [fold] action. I did not find how to change the key binding.

Thx

**Comment by nounoursheureux** [comment]
I have an AZERTY keyboard and I can type ] with Alt+) . And I don't see how your issue is related to atom-git-control :question:

**Comment by kylekatarnls** [comment]
Oh sorry, yes, it is atom-core related I think. AltGr + ) trigger Fold, I will try to disable plugins.
