### ISSUE TITLE
Please fix deprecations; deprecated methods will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [jacogr/atom-git-control#79]
On June 1st this package will break. This is a neat package with many users. It looks like maybe just publishing a new release will fix these issues. See https://gist.github.com/benogle/6d09e295c84b717ef9b4 for a list of deprecations from git-control

For more information, see: https://github.com/atom/atom/issues/6867

**Comment by nounoursheureux** [comment]
Actually all the deprecations are fixed ( #57 #66 ), but the fixes are not released and are only in the development version. Thanks for the feedback :+1:

**Comment by jacogr** [comment]
Released 0.3.0 with https://github.com/jacogr/atom-git-control/commit/008fe7491bdeaaaf85bee4c17f8c08087ba8d68c, hoping @MarcelMue approves.

**Comment by MarcelMue** [comment]
Yes seems good to me, I was very busy lately with uni and slacked a bit. Sorry for the delay but I hope it's all good now!
