### ISSUE TITLE
Push window is inactive on first commit

### ISSUE THREAD

**Issue by Trudko** [jacogr/atom-git-control#8]
Hi :), I really like your package so far! I think I found one small problem with it.

I have cloned new git repo. 
Committed first commit.
Push button seemed disabled(was grey) but push worked. 
Remote was added to remote list.

When I tried second commit push button was active.

**Comment by jacogr** [comment]
Thank you, will retrace your steps and try to provide a fix.

**Comment by Trudko** [comment]
@jacogr how about if I take a look at this first? I have bit free time today so I can take a look. I am happy to help.

**Comment by jacogr** [comment]
Perfect, I appreciate any help, suggestions for improvements, cleanups, PRs, etc.

**Comment by Trudko** [comment]
Well what I noticed is that when I clone https://github.com/Trudko/my-package.git and run git control push is disabled. What I am curious though is why to disable it at all? I would disabled it only if there is not remote maybe.

**Comment by jacogr** [comment]
It will be inactive if neither of the following is true -

1. Local changes have been made and committed - no need to push if there is nothing to push
2. The local has a remote - no need to push is there is nowhere to push to

**Comment by Trudko** [comment]
I think the first scenario is the problem then. Do you update remote branches automatically or do I have to use fetch myself? If second is the case that might be a problem. I think ideally package should update remote branches automatically or make push available always but if there is nothing to push just show user the mssage.

PS: Even if pull and push are disabled when I click them the commands still run.

**Comment by jacogr** [comment]
All branches are updated automatically via fetch. In theory you should never need to call "fetch" yourself, rather as soon as you switch to the package, it updates.

I have been trying to replicate with new clones, thus far not much success.

PS: Yes, currently the gray is more of an indicator than a disabler. (Not intended this way initially, just wanted to get it out there and fed back in it's current form. Same goes for all command, except "commit" which will check for available/selected files.)

**Comment by Trudko** [comment]
Have you tried to clone the link I posted?

if gray is indicator isn't that confusing? At least it confused me, because I would though that if commit and reset doesn do anything while grayed out , so shouldn't pull and push.

**Comment by jacogr** [comment]
It is confusing, not supposed to be the "right way". Currently it is half-way there - the indicator is there, the block of functionality is not.

Repeated my test just now:

1. Cloned repo on command-line
2. Opened git-control, push was disabled (as expected, no local changes has been made)
3. Change made, push still disabled (as expected, nothing committed as of yet)
4. Change committed, push now enabled (as expected, branch also shows up arrow for local changes that should be pushed to remote)

**Comment by Trudko** [comment]
Ok try this:

1. Mkdir test.
2. cd test
3. git init
4. git add 
5. git remote add origin https://github.com/Trudko/my-package.git
6. atom
7. add new file test.txt
8. run git control
9. commit
10. push buttion is disabled.

**Comment by jacogr** [comment]
Ok, I can now see what is happening. Confusing the fact that there are no remote branches (no fetch called) with not having an origin. I'll see what options I have to determine the actual origin here.

**Comment by jacogr** [comment]
Just pushed 0.1.8 that works for the cases where (a) no local remote exists (previous issue, needs to continue working) & (b) that addresses your issue here, i.e. from replicating the steps provided.

Please take a peek and let me know if the issue persists.

**Comment by Trudko** [comment]
Looks great thanks!
