### ISSUE TITLE
Merge commits to another branches with cherry-pick

### ISSUE THREAD

**Issue by kylekatarnls** [jacogr/atom-git-control#84]
Hi,

I did not find how to do git cherry-pick with atom-git-control. I imagine the feature like this :
Next to the [Merge] button, a [Cherry pick] button.
When you click on that button, the list of commit that can be picked appears with checkboxes.
You can check commits
Then when at least one commit is checked, a [Pick] button is enabled
When you click on [Pick] git cherry-pick is applied on each checked commit.

I think it would be nice to have it, if no one already began such a feature, I might do it.

**Comment by davidak** [comment]
@kylekatarnls please do it :)
