### ISSUE TITLE
Confirm dangerous commands

### ISSUE THREAD

**Issue by WoodyWoodsta** [jacogr/atom-git-control#86]
Having the "reset" button right next to the "commit" button, and without a confirmation to reset makes me a little nervous.

**Comment by hellerbarde** [comment]
Yeah, a confirmation on reset would be really cool.

**Comment by matheo** [comment]
+1
The commit @ba36cbe seems to add the dialog but I just installed the v0.3.0 and the dialog is not shown. Can we have a v0.3.1 before a tragedy? :P 
Thanks for the time @MarcelMue

**Comment by Trexology** [comment]
+10000000000

The tragedy just happened to me.... 2hrs of work *poof* gone!

**Comment by hellerbarde** [comment]
Unfortunately, I don't use Atom anymore. Is this still a problem? can someone confirm or deny, please?

**Comment by davidak** [comment]
I can confirm that this is fixed in 0.7.1.

![bildschirmfoto 2016-07-14 um 12 48 03](https://cloud.githubusercontent.com/assets/91113/16837101/803a15d8-49c1-11e6-9e4a-3bb27970c769.png)

/clode @jacogr
