### ISSUE TITLE
Files in folders aren't listed separately

### ISSUE THREAD

**Issue by Trudko** [jacogr/atom-git-control#9]
I have created new folder(foo) in projects root and added new file(bar.js) inside of it. In workspace view I have one item to add foo/ instead of foo/bar.js. I am not therefore sure how to for example add only one file from sub folder if there are more than just a one.

**Comment by jacogr** [comment]
Yes, I've seen this one myself. 

I'll do some investigation to see if I can get better information on these added folders.

**Comment by jacogr** [comment]
Additional flag passed to git status to show the status of all files in newly created folders. Version 0.1.7 published that addresses the issue here, please give it a spin and see if it resolves it for you.

**Comment by Trudko** [comment]
Yes this seems to be working now, good job!

**Comment by jacogr** [comment]
Excellent. 

Actually it was driving me crazy as well, your report just gave me the final push to actually look for a real solution. Thank you.
