### ISSUE TITLE
Greyed out Push/Pull Buttons are still active

### ISSUE THREAD

**Issue by hellerbarde** [jacogr/atom-git-control#90]
I have a repository with a https upstream and the Push/Pull buttons are greyed out. I don't know why, but when I click them, they still do what they usually do.

I'm not sure whether the bug is that they are greyed out or whether they still work.

**Comment by MarcelMue** [comment]
Sounds like a bug to me, I haven't encountered it though. Help fixing it is appreciated :+1:

**Comment by MarcelMue** [comment]
Looking at your pull request I assume that the buttons are supposed to be greyed out and not work?

**Comment by hellerbarde** [comment]
:+1: LGTM! It fixes the bug that the buttons should not be activating something when they are "deactivated".

In a broader context: Is there no built in way to have data bindings from model to view in Atom? I feel like digging around in the classes of the relevant DOM node is a little dirty

**Comment by MarcelMue** [comment]
@hellerbarde I don't know of a way to have data bindings in atom as they provide an api you can work with but no advanced framework ( like angular or something ). So packages manipulate the DOM themselves and filtering / searching for certain DOM nodes is a (nasty) effect of that.

I will merge @rkmax PR in a minute as I have been waiting to see if it fixes the issue (I was too lazy to try and recreate the issue :D ).

**Comment by rkmax** [comment]
I assume that if the button has `.inactive` class click must not work

**Comment by MarcelMue** [comment]
@rkmax Yes you are correct, I was just unsure what the initial issue was.

Thanks for the contributions :+1:
