### ISSUE TITLE
The diff view always is empty

### ISSUE THREAD

**Issue by rkmax** [jacogr/atom-git-control#91]
The diff view always is empty

![captura de pantalla de 2015-07-18 01-18-06](https://cloud.githubusercontent.com/assets/395707/8760581/e49134d4-2cea-11e5-9ac9-a0ca661a3431.png)

**Comment by MarcelMue** [comment]
I am a bit confused by your report. What happens if you click Compare (which should usually populate the diff view) ? Are there any errors thrown?

**Comment by rkmax** [comment]
No. I can see errors but the diff view it's empty always, even if I clicked some file to compare

**Comment by MarcelMue** [comment]
Okay I marked this as a bug, does this happen with every git repository you work on? What Atom version are you using?

**Comment by rkmax** [comment]
Yes, it's happening with all repositories. I'm using atom 1.0.2, git control 0.3.0, let me know if you need further information

**Comment by MarcelMue** [comment]
I think your issue could be related to #40 but both issues seem to affect a small user base and I was unable to find a reason for the behavior so far ( some users have reported similar issues appearing and then disappearing again seemingly randomly which makes it hard to find the problem )

**Comment by rkmax** [comment]
is there any chance git-control may have conflicts with another extensions?

**Comment by rkmax** [comment]
@MarcelMue I reinstalled atom and now works! (mysteries of the universe). I think was something with my extensions

**Comment by alexanderadam** [comment]
Having the exact same issue just now.

I deleted a file (which was previously committed) and then I got an error message in the git-control console area:
```
> git --no-pager diff DELETED_FILENAME
fatal: DELETED_FILENAME: no such path in the working tree.
'git --no-pager diff DELETED_FILENAME'
```

The reason that it depends on a commit with a deleted file explains why the problem seems to appear "randomly".

Anyway: @jacogr your extension is really awesome!
Thank you for it.
