### ISSUE TITLE
Multiline commit message are incorrectly marked as too long 

### ISSUE THREAD

**Issue by hellerbarde** [jacogr/atom-git-control#94]
When a commit message is longer than 80 characters, it displays as red, even when the 80 characters are split up over multiple lines. I will have a look at fixing it.

**Comment by MarcelMue** [comment]
The colored characters have been introduced in #65 and currently simply counts the characters of the commit message.

**Comment by hellerbarde** [comment]
That's what I figured. I will work on it. shouldn't take too long.

**Comment by flying-sheep** [comment]
ah great, just stumbled upon this and now i see it’s already fixed on master :smile:
